SELECT COUNT(tbl.POST_ID) AS NUM, tbl.USER_ID, tbl.POST_ID, tbl.CREATED_AT
FROM (SELECT POST_ID, USER_ID, CREATED_AT FROM post WHERE CREATED_AT BETWEEN '2020-03-01' AND '2020-03-02') as tbl
GROUP BY tbl.USER_ID