SELECT names.NAME
FROM (SELECT COUNT(tab.POST_ID) AS NUM, NAME
FROM (SELECT CREATED_AT, POST_ID, user.USER_ID, user.NAME FROM user
INNER JOIN post
ON user.USER_ID=post.USER_ID
WHERE CREATED_AT BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 1 DAY)) AS tab
GROUP BY tab.USER_ID) AS names
WHERE names.NUM > 2